spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/vue
      username: agd
      password: '123'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false

server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always

security:
  oauth2:
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true
    client:
      registration:
        google:
      clientId: 253277319034-e8fm0o4enikcjrbrtg6bak3lelduc5kr.apps.googleusercontent.com
      clientSecret: ${clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile
app:
  jwtSecret: fdghasdfg
  jwtExpirationMs: 300000